#!/usr/bin/env python3
"""Build js/data.js from the Big Ambitions spreadsheet.

Usage: python3 scripts/build_data.py [path/to/xlsx]
"""
import json, pathlib, re, sys
import openpyxl

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_XLSX = ROOT / "data" / "BigAmbitions_Items_and_Prices.xlsx"
OUT = ROOT / "js" / "data.js"


def rows(ws):
    return [r for r in ws.iter_rows(min_row=2, values_only=True) if r[0]]


def split(cell):
    return [p.strip() for p in str(cell or "").split(",") if p.strip()]


def build(xlsx_path):
    wb = openpyxl.load_workbook(xlsx_path)
    items = {r[0]: r for r in rows(wb["Items"])}
    ingredients = {}
    for r in rows(wb["Recipe Ingredients"]):
        ingredients.setdefault(r[0], []).append([r[1], r[2]])
    recipes = [[r[0], r[2], split(r[4]), ingredients[r[0]]] for r in rows(wb["Recipes"])]

    prices = {r[0]: r[3] for r in rows(wb["Furniture & Equipment"])}
    machines = {}
    for _, _, ms, _ in recipes:
        for m in ms:
            machines.setdefault(m, prices[m])

    used = []
    for name, _, _, ins in recipes:
        for n in [name] + [i[0] for i in ins]:
            if n not in used:
                used.append(n)
    item_data = {}
    for n in used:
        r = items[n]
        # "*" marks importers that only stock the item with the "all products" setting on
        importers = sorted(i.rstrip("*").strip() for i in split(r[3]))
        item_data[n] = [r[4], r[5], r[8], r[10], r[13] or "", importers]

    source = next(r[1] for r in wb["Read Me"].iter_rows(values_only=True) if r[0] == "Source")
    pulled = re.search(r"\d{4}-\d{2}-\d{2}", source).group(0)
    meta = {"pulled": pulled, "recipes": len(recipes), "items": len(item_data)}
    return {"R": recipes, "I": item_data, "M": machines, "meta": meta}


def main():
    xlsx = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_XLSX
    data = build(xlsx)
    OUT.write_text(
        "/* GENERATED by scripts/build_data.py from the xlsx. Do not edit by hand. */\n"
        f"var DATA = {json.dumps(data, separators=(',', ':'))};\n"
        'if (typeof module !== "undefined") module.exports = DATA;\n'
    )
    print(f"Wrote {OUT.relative_to(ROOT)}: {data['meta']}")


if __name__ == "__main__":
    main()
